gantt
    title Project Timeline
    dateFormat YYYY-MM-DD
    section Design
    Spec        :done,    des1, 2026-01-01, 7d
    Mockups     :active,  des2, after des1, 5d
    section Build
    CLI         :         dev1, after des2, 10d
    GUI         :         dev2, after des2, 12d
